# Generated by Django 4.0.4 on 2022-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Application ID'),
        ),
    ]
